server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    gateway:
      routes:
        - id: ItemService
          uri: lb://ItemService
          predicates:
            - Path=/item,/item/**
        - id: UnitService
          uri: lb://UnitService
          predicates:
            - Path=/unit, /unit/**
        - id: NotificationService
          uri: lb://NotificationService
          predicates:
            - Path=/notification, /notification/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

